name: Sync Selected Files to GitVerse

on:
  schedule:
    # Запуск каждые 4 часа (можно настроить чаще/реже)
    - cron: '0 */4 * * *'
  # Позволяет запустить синхронизацию вручную кнопкой
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонируем ваш текущий репозиторий на GitHub
      - name: Checkout local repo
        uses: actions/checkout@v4

      # 2. Скачиваем актуальные файлы из ЧУЖОГО репозитория
      - name: Download files from foreign GitHub
        run: |
          # Пример для файла №1 (Замените URL и имя файла на свои)
          curl -s -L "https://github.com/igareck/vpn-configs-for-russia/blob/main/Vless-Reality-White-Lists-Rus-Mobile.txt" -o "igareck.txt"
          
          # Пример для файла №2 
          #curl -s -L "https://githubusercontent.com" -o "config.json"

      # 3. Проверяем изменения и пушим их в GitHub и GitVerse
      - name: Commit and Push changes
        env:
          GV_TOKEN: ${{ secrets.GITVERSE_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          if [ -n "$(git status --porcelain)" ]; then
            echo "Обнаружены обновления в чужих файлах! Фиксируем изменения..."
            
            git add .
            git commit -m "Авто-обновление внешних файлов: $(date +'%Y-%m-%d %H:%M')"
            
            # 1. Сначала сохраняем изменения у себя на GitHub
            git push origin main
            
            # 2. Безопасно настраиваем связь с GitVerse
            # Если удаленный сервер gitverse уже есть — обновляем URL, если нет — создаем
            git remote set-url gitverse "https://token:${GV_TOKEN}@gitverse.ru/Trekkku/github_trekkku.git" 2>/dev/null || \
            git remote add gitverse "https://token:${GV_TOKEN}@gitverse.ru/Trekkku/github_trekkku.git"
            
            # 3. Отправляем изменения на GitVerse
            git push gitverse main --force
            
            echo "Файлы успешно синхронизированы с GitVerse!"
          else
            echo "Изменений в чужих файлах нет. Синхронизация не требуется."
          fi
